// Design tokens and constants

export const colors = {
  primary: "#2E7D32",
  primaryLight: "#4CAF50",
  primaryDark: "#1B5E20",
  accent: "#FF6F00",
  accentLight: "#FF9800",
  bgPrimary: "#ffffff",
  bgSecondary: "#F5F5F5",
  bgTertiary: "#FAFAFA",
  textPrimary: "#333333",
  textSecondary: "#666666",
  textMuted: "#999999",
  border: "#E0E0E0",
  borderLight: "#EEEEEE",
} as const;

export const breakpoints = {
  sp: 768,
  tb: 1024,
  pc: 1025,
} as const;

export const animations = {
  fadeIn: {
    duration: 0.6,
    ease: "easeOut",
  },
  countUp: {
    duration: 1.5,
  },
  hover: {
    duration: 0.3,
    scale: 1.02,
    translateY: -5,
  },
  pageTransition: {
    duration: 0.4,
  },
} as const;

export const navigation = {
  standard: [
    { href: "/templates/standard", label: "HOME" },
    { href: "/templates/standard/about", label: "会社概要" },
    { href: "/templates/standard/service", label: "サービス" },
    { href: "/templates/standard/recruit", label: "採用情報" },
    { href: "/templates/standard/contact", label: "お問い合わせ" },
  ],
  recruitMagazine: [
    { href: "/templates/recruit-magazine", label: "HOME" },
    { href: "/templates/recruit-magazine/about", label: "会社を知る" },
    { href: "/templates/recruit-magazine/work", label: "仕事を知る" },
    { href: "/templates/recruit-magazine/people", label: "社員を知る" },
    { href: "/templates/recruit-magazine/culture", label: "働く環境" },
    { href: "/templates/recruit-magazine/recruit", label: "募集要項" },
    { href: "/templates/recruit-magazine/entry", label: "エントリー" },
  ],
  leadgenMinimal: [
    { href: "/templates/leadgen-minimal", label: "HOME" },
    { href: "/templates/leadgen-minimal/service", label: "サービス" },
    { href: "/templates/leadgen-minimal/works", label: "施工実績" },
    { href: "/templates/leadgen-minimal/contact", label: "お問い合わせ" },
  ],
  leadgenVisual: [
    { href: "/templates/leadgen-visual", label: "HOME" },
    { href: "/templates/leadgen-visual/about", label: "会社概要" },
    { href: "/templates/leadgen-visual/service", label: "事業内容" },
    { href: "/templates/leadgen-visual/works", label: "加工実績" },
    { href: "/templates/leadgen-visual/contact", label: "お問い合わせ" },
  ],
  trustVisual: [
    { href: "/templates/trust-visual", label: "HOME" },
    { href: "/templates/trust-visual/about", label: "事務所概要" },
    { href: "/templates/trust-visual/service", label: "専門分野" },
    { href: "/templates/trust-visual/lawyers", label: "弁護士紹介" },
    { href: "/templates/trust-visual/case", label: "解決事例" },
    { href: "/templates/trust-visual/contact", label: "お問い合わせ" },
  ],
  authorityMinimal: [
    { href: "/templates/authority-minimal", label: "HOME" },
    { href: "/templates/authority-minimal/about", label: "会社概要" },
    { href: "/templates/authority-minimal/service", label: "サービス" },
    { href: "/templates/authority-minimal/case", label: "導入事例" },
    { href: "/templates/authority-minimal/knowledge", label: "ナレッジ" },
    { href: "/templates/authority-minimal/ceo", label: "代表紹介" },
    { href: "/templates/authority-minimal/recruit", label: "採用情報" },
    { href: "/templates/authority-minimal/contact", label: "お問い合わせ" },
  ],
  fullorder: [
    { href: "/templates/fullorder", label: "HOME" },
  ],
} as const;

export const templates = [
  {
    id: "standard",
    name: "標準テンプレート",
    subtitle: "企業HP標準",
    description: "企業HPの標準構成。会社概要、サービス、採用、お問い合わせなど基本ページを網羅。",
    features: ["6ページ構成", "汎用性が高い", "SEO対策済み", "どの業種にも対応"],
    suitableFor: ["初めてHPを作る企業", "標準的な情報発信をしたい企業", "コストを抑えたい企業"],
    color: "#1a2744",
    href: "/templates/standard",
    image: "/images/templates/standard/thumbnail.jpg",
    status: "available" as const,
    repo: "template-standard",
    pages: 6,
    company: "中部建設株式会社",
    date: "2026/01/18",
  },
  {
    id: "recruit-magazine",
    name: "採用サイト（マガジン形式）",
    subtitle: "読ませるエディトリアル",
    description: "採用特化のマガジン形式。社員インタビュー、働く環境、キャリアパスを深く伝える。",
    features: ["7ページ構成", "インタビュー重視", "Magazine表現", "余白で語るデザイン"],
    suitableFor: ["採用に力を入れている企業", "社員の魅力を伝えたい企業", "文章で訴求したい企業"],
    color: "#2d3748",
    href: "/templates/recruit-magazine",
    image: "/images/templates/recruit-magazine/thumbnail.jpg",
    status: "available" as const,
    repo: "template-recruit-magazine",
    pages: 7,
    company: "株式会社ネクストステージ",
    date: "2026/01/18",
  },
  {
    id: "leadgen-minimal",
    name: "リード獲得型（ミニマル）",
    subtitle: "CV最短ルート設計",
    description: "コンバージョン最優先のミニマル設計。余白とタイポグラフィで信頼感を演出。",
    features: ["4ページ構成", "CV導線最適化", "ミニマルデザイン", "フォーム重視"],
    suitableFor: ["問い合わせを増やしたい企業", "リード獲得が目的の企業", "シンプルなサイトを好む企業"],
    color: "#1e40af",
    href: "/templates/leadgen-minimal",
    image: "/images/templates/leadgen-minimal/thumbnail.jpg",
    status: "available" as const,
    repo: "template-leadgen-minimal",
    pages: 4,
    company: "スカイリフォーム株式会社",
    date: "2026/01/14",
  },
  {
    id: "leadgen-visual",
    name: "地域密着型（ビジュアル）",
    subtitle: "地域商圏×SEO",
    description: "地域密着型ビジネス向け。施工実績ギャラリー、エリア情報、地域SEOに最適化。",
    features: ["5ページ構成", "施工実績重視", "地域SEO対応", "ビジュアル豊富"],
    suitableFor: ["地域密着のサービス業", "施工実績を見せたい企業", "エリア限定のビジネス"],
    color: "#1e3a5f",
    href: "/templates/leadgen-visual",
    image: "/images/templates/leadgen-visual/thumbnail.jpg",
    status: "available" as const,
    repo: "template-leadgen-visual",
    pages: 5,
    company: "三河精密工業株式会社",
    date: "2026/01/13",
  },
  {
    id: "trust-visual",
    name: "信頼構築型（ビジュアル）",
    subtitle: "社会的証明の最大化",
    description: "実績・資格・メディア掲載など社会的証明を前面に。写真・動画で信頼感を醸成。",
    features: ["6ページ構成", "実績・資格重視", "メディア掲載", "権威性の可視化"],
    suitableFor: ["専門性をアピールしたい企業", "実績が豊富な企業", "士業・コンサル"],
    color: "#1a365d",
    href: "/templates/trust-visual",
    image: "/images/templates/trust-visual/thumbnail.jpg",
    status: "available" as const,
    repo: "template-trust-visual",
    pages: 6,
    company: "あおぞら法律事務所",
    date: "2026/01/13",
  },
  {
    id: "authority-minimal",
    name: "権威性訴求（ミニマル）",
    subtitle: "専門性・実績で説得",
    description: "専門性と実績を論理的に訴求。ミニマルデザインで品格と信頼感を表現。",
    features: ["8ページ構成", "専門性重視", "論理的構成", "ミニマルデザイン"],
    suitableFor: ["コンサルティング企業", "BtoB企業", "専門サービス業"],
    color: "#18181b",
    href: "/templates/authority-minimal",
    image: "/images/templates/authority-minimal/thumbnail.jpg",
    status: "available" as const,
    repo: "template-authority-minimal",
    pages: 8,
    company: "株式会社テックフロンティア",
    date: "2026/01/12",
  },
  {
    id: "fullorder",
    name: "フルオーダー",
    subtitle: "完全カスタム",
    description: "ページ構成なしの完全カスタムテンプレート。自由にページを追加して構築可能。",
    features: ["ページ数自由", "完全カスタム", "site.jsonで管理", "柔軟な構成"],
    suitableFor: ["独自の構成が必要な企業", "特殊な業種", "オリジナリティを重視する企業"],
    color: "#6b7280",
    href: "/templates/fullorder",
    image: "/images/templates/fullorder/thumbnail.jpg",
    status: "available" as const,
    repo: "template-fullorder",
    pages: 0,
    company: "フルオーダーテンプレート",
    date: "2026/01/10",
  },
] as const;
